# Generated by Django 4.0.3 on 2022-03-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0009_assessmentphase_room_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('csv', models.FileField(upload_to='')),
                ('assessment_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_sheets', to='schedule.assessmentphase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
