# Generated by Django 4.0.3 on 2022-04-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_window_position_alter_assessmentphase_category_and_more'),
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningsheet',
            name='assessment_phase',
        ),
        migrations.AddField(
            model_name='planningsheet',
            name='window',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planning_sheets', to='schedule.window'),
            preserve_default=False,
        ),
    ]
