# Generated by Django 4.0.3 on 2022-04-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_sheetrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SheetRecord',
        ),
    ]
