# Generated by Django 4.0.3 on 2022-05-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_delete_sheetrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsheet',
            name='is_filled_out',
            field=models.BooleanField(default=False),
        ),
    ]
