# Generated by Django 4.0.3 on 2022-03-29 16:10

import core.utils.datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('year', models.IntegerField(default=core.utils.datetime.current_year, validators=[django.core.validators.MinValueValidator(2021)])),
                ('semester', models.CharField(choices=[('spring', 'Spring Semester'), ('fall', 'Fall Semester')], max_length=32)),
                ('category', models.CharField(choices=[('main', 'Main Phase'), ('reassessments', 'Re-Assessments')], max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='user.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
