# Generated by Django 4.0.3 on 2022-03-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assessment_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='schedule.assessmentphase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
