# Generated by Django 4.0.3 on 2022-03-30 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='block_length',
            field=models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(420)]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('exam_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(360)])),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedule.window')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
