# Generated by Django 4.0.3 on 2022-03-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_block_exam_length_blocktemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='block',
            name='window',
        ),
        migrations.AddField(
            model_name='block',
            name='template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedule.blocktemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BlockSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_slots', to='schedule.window')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='block',
            name='block_slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='schedule.blockslot'),
            preserve_default=False,
        ),
    ]
