# Generated by Django 4.0.3 on 2022-03-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_block_start_time_remove_block_window_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slots', to='schedule.block')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='blocktemplate',
            name='windows',
            field=models.ManyToManyField(blank=True, null=True, related_name='block_templates', to='schedule.window'),
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
