# Generated by Django 4.0.3 on 2022-03-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_blocktemplate_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentphase',
            name='room_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
