# Generated by Django 4.0.3 on 2022-03-31 21:59

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220329_1821'),
        ('schedule', '0009_assessmentphase_room_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentphase',
            name='organization',
            field=models.ForeignKey(default=user.models.code_university_id, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='user.organization'),
        ),
    ]
