# Generated by Django 4.0.3 on 2022-04-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_assessmentphase_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentphase',
            options={'ordering': ['-year']},
        ),
    ]
