# Generated by Django 4.0.3 on 2022-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_assessmentphase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentphase',
            name='category',
            field=models.CharField(choices=[('main', 'Main Phase'), ('reassessments', 'Re-Assessments')], default='main', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='assessmentphase',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'semester', 'category'), name='unique_phase'),
        ),
        migrations.AddConstraint(
            model_name='window',
            constraint=models.UniqueConstraint(fields=('assessment_phase', 'position'), name='unique_position_per_phase'),
        ),
    ]
