# Generated by Django 4.0.3 on 2022-05-01 13:55

from django.db import migrations
from django.utils.timezone import now


def forward(apps, schema_editor):
    BlockTemplate = apps.get_model('schedule', 'BlockTemplate')
    BlockTemplate.objects.create(
        block_length=180,
        exam_length=20,
        exam_start_times=[0, 20, 40, 80, 100, 140, 160],
        created=now(),
        modified=now()
    )
    BlockTemplate.objects.create(
        block_length=180,
        exam_length=30,
        exam_start_times=[0, 30, 60, 120, 150],
        created=now(),
        modified=now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_window_position_alter_assessmentphase_category_and_more'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
