# Generated by Django 4.0.3 on 2022-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20220501_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ['assessment_phase', 'position']},
        ),
    ]
