# Generated by Django 4.0.3 on 2022-05-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_block_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='penalty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
