# Generated by Django 4.0.3 on 2022-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_schedule_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='scheduling_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
