# Generated by Django 4.0.4 on 2022-06-08 15:23

from django.db import migrations
from django.utils.timezone import now


def provide_default_phase(apps, schema_editor):
    Organization = apps.get_model('user', 'Organization')
    code_uni = Organization.objects.get(name='CODE University')

    AssessmentPhase = apps.get_model('schedule', 'AssessmentPhase')
    AssessmentPhase.objects.get_or_create(
        organization=code_uni,
        year=2022,
        semester='spring',
        category='main',
        defaults={'created': now(), 'modified': now()},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_window_scheduling_ongoing'),
        ('user', '0004_auto_20220329_1821')
    ]

    operations = [
        migrations.RunPython(provide_default_phase)
    ]
