# Generated by Django 4.0.3 on 2022-03-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_blocktemplate_windows'),
        ('user', '0004_auto_20220329_1821'),
        ('staff', '0004_assessor_available_blocks_helper_available_blocks'),
        ('exam', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='user.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='user.organization'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('code', models.CharField(max_length=64)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='staff.assessor')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='staff.helper')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.student')),
                ('time_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.examslot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
