# Generated by Django 4.0.3 on 2022-04-30 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_module_alternative_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='alternative_length',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='module',
            name='standard_length',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
