# Generated by Django 4.0.3 on 2022-05-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_window_position_alter_assessmentphase_category_and_more'),
        ('exam', '0006_module_alternative_length_module_standard_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='windows',
            field=models.ManyToManyField(related_name='modules', to='schedule.window'),
        ),
    ]
