# Generated by Django 4.0.3 on 2022-05-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_module_windows'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['code']},
        ),
    ]
