# Generated by Django 4.0.3 on 2022-05-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_window_options'),
        ('exam', '0008_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='window',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schedule.window'),
            preserve_default=False,
        ),
    ]
