# Generated by Django 4.0.3 on 2022-05-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exam_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='style',
            field=models.CharField(choices=[('standard', 'Standard'), ('alternative', 'Alternative')], default=('standard', 'Standard'), max_length=32),
            preserve_default=False,
        ),
    ]
