# Generated by Django 4.0.3 on 2022-03-29 16:21

from django.db import migrations
from django.utils.timezone import now


def forwards(apps, schema_editor):
    """Create organization for CODE University"""
    Organization = apps.get_model('user', 'Organization')
    Organization.objects.get_or_create(
        name='CODE University',
        created=now(),
        modified=now()
    )


def backwards(apps, schema_editor):
    Organization = apps.get_model('user', 'Organization')
    Organization.objects.filter(name='CODE University').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_organization'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=backwards)
    ]
