# Generated by Django 4.0.3 on 2022-03-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0007_examslot_alter_blocktemplate_windows_delete_slot'),
        ('user', '0004_auto_20220329_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(blank=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('assessment_phases', models.ManyToManyField(related_name='assessors', to='schedule.assessmentphase')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessors', to='user.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
