# Generated by Django 4.0.3 on 2022-03-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessor',
        ),
    ]
