# Generated by Django 4.0.3 on 2022-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_blocktemplate_windows'),
        ('staff', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='available_blocks',
            field=models.ManyToManyField(related_name='%(class)s', to='schedule.blockslot'),
        ),
        migrations.AddField(
            model_name='helper',
            name='available_blocks',
            field=models.ManyToManyField(related_name='%(class)s', to='schedule.blockslot'),
        ),
    ]
