# Generated by Django 4.0.3 on 2022-04-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_assessor_available_blocks_helper_available_blocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessor',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='helper',
            options={'ordering': ['email']},
        ),
    ]
