# Generated by Django 4.0.3 on 2022-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_window_options'),
        ('staff', '0005_alter_assessor_options_alter_helper_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='windows',
            field=models.ManyToManyField(related_name='%(class)s', to='schedule.window'),
        ),
        migrations.AddField(
            model_name='helper',
            name='windows',
            field=models.ManyToManyField(related_name='%(class)s', to='schedule.window'),
        ),
    ]
