# Generated by Django 4.0.4 on 2022-06-02 21:31

import os

from django.db import migrations

import google.auth
from google.cloud import secretmanager_v1 as sm
from google.auth.exceptions import DefaultCredentialsError


def access_secrets(secret_keys):
    secrets = {}
    _, project = google.auth.default()

    if project:
        client = sm.SecretManagerServiceClient()

        for s in secret_keys:
            name = f"projects/{project}/secrets/{s}/versions/latest"
            payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
            secrets[s] = payload

    return secrets


def createsuperuser(apps, schema_editor):
    try:
        settings = ["SUPERUSER", "SUPERPASS"]
        if not all(k in os.environ.keys() for k in set(settings)):
            secrets = access_secrets(settings)
            username = secrets["SUPERUSER"]
            password = secrets["SUPERPASS"]
        else:
            username = os.environ["SUPERUSER"]
            password = os.environ["SUPERPASS"]

        # Create a new user using acquired password
        from user.models import User

        User.objects.create_superuser(username, password=password)
    except DefaultCredentialsError:
        pass


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(createsuperuser)]

