steps:
    - id: 'migrate'
      name: 'gcr.io/google-appengine/exec-wrapper'
      args: ['-i', 'gcr.io/${PROJECT_ID}/${_SERVICE}:prod-latest',
             '-s', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
             '-e', 'PROJECT_ID=${PROJECT_ID}',
             "-e", "APPLICATION_STAGE=production",
             "--", "python", "manage.py", "migrate"]

    - id: "collect static"
      name: "gcr.io/google-appengine/exec-wrapper"
      args: [
            "-i",
            "gcr.io/$PROJECT_ID/${_SERVICE}:prod-latest",
            "-s",
            "${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}",
            "-e",
            "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}",
            "--",
            "python",
            "manage.py",
            "collectstatic",
            "--verbosity",
            "2",
            "--no-input"]

images:
 - "gcr.io/$PROJECT_ID/${_SERVICE}:prod-latest"

substitutions:
   _SERVICE: examsched
   _REGION: europe-west3
   _INSTANCE_NAME: postgresql
   _SECRET_SETTINGS_NAME: django_settings
